server:
  registerDefaultExceptionMappers: false
  adminConnectors:
    - type: http
      port: 9092

database:
  driverClass: org.postgresql.Driver
  url: jdbc:postgresql://localhost:5432/field
  user: postgres
  password:

  #db connection properties
  initialSize: 1
  minSize: 1
  maxSize: 4

  properties:
    charSet: UTF-8
