---
food-premises:
  index-entry-number: "8"
  entry-number: "8"
  entry-timestamp: "2016-04-21T10:14:21Z"
  key: "food-premises"
  item:
  - text: "Premises which prepare and serve food"
    phase: "alpha"
    fields:
    - "food-premises"
    - "name"
    - "business"
    - "food-premises-types"
    - "local-authority"
    - "premises"
    - "start-date"
    - "end-date"
    register: "food-premises"
    registry: "food-standards-agency"
country:
  index-entry-number: "3"
  entry-number: "3"
  entry-timestamp: "2016-04-21T10:14:21Z"
  key: "country"
  item:
  - text: "British English-language names and descriptive terms for countries"
    phase: "alpha"
    fields:
    - "country"
    - "name"
    - "official-name"
    - "citizen-names"
    - "start-date"
    - "end-date"
    register: "country"
    registry: "foreign-commonwealth-office"
registry:
  index-entry-number: "17"
  entry-number: "17"
  entry-timestamp: "2016-04-21T10:14:21Z"
  key: "registry"
  item:
  - text: "Bodies responsible for the maintainance of one or more registers"
    phase: "alpha"
    fields:
    - "registry"
    register: "registry"
    registry: "cabinet-office"
address:
  index-entry-number: "1"
  entry-number: "1"
  entry-timestamp: "2016-04-21T10:14:21Z"
  key: "address"
  item:
  - text: "Postal addresses in the UK"
    phase: "alpha"
    fields:
    - "address"
    - "property"
    - "street"
    - "locality"
    - "town"
    - "area"
    - "postcode"
    - "country"
    - "latitude"
    - "longitude"
    register: "address"
    registry: "office-for-national-statistics"
    copyright: "Contains Ordnance Survey data © Crown copyright & database right 2015\n\
      \ Contains Royal Mail data © Royal Mail copyright & database right 2015\n"
postcode:
  index-entry-number: "13"
  entry-number: "13"
  entry-timestamp: "2016-04-21T10:14:21Z"
  key: "postcode"
  item:
  - text: "Postal codes which may appear in a UK address"
    phase: "alpha"
    fields:
    - "postcode"
    - "point"
    register: "postcode"
    registry: "office-for-national-statistics"
    copyright: "Contains National Statistics data © [Crown copyright and database right\
      \ 2013](http://www.nationalarchives.gov.uk/doc/open-government-licence/),\n Contains\
      \ Ordnance Survey data © [Crown copyright and database right 2013](http://www.ordnancesurvey.co.uk/oswebsite/docs/licences/os-opendata-licence.pdf),\n\
      \ Contains Royal Mail data © [Royal Mail copyright and database right 2013](http://www.dfpni.gov.uk/lps/index/copyright_licensing_publishing.htm)"
food-premises-rating:
  index-entry-number: "6"
  entry-number: "6"
  entry-timestamp: "2016-04-21T10:14:21Z"
  key: "food-premises-rating"
  item:
  - text: "Food hygiene inspection ratings"
    phase: "alpha"
    fields:
    - "food-premises-rating"
    - "food-premises"
    - "food-premises-rating-value"
    - "food-premises-rating-hygiene-score"
    - "food-premises-rating-structural-score"
    - "food-premises-rating-confidence-in-management-score"
    - "local-authority"
    - "food-premises-rating-reply"
    - "start-date"
    - "inspector"
    - "end-date"
    register: "food-premises-rating"
    registry: "food-standards-agency"
industry:
  index-entry-number: "10"
  entry-number: "10"
  entry-timestamp: "2016-04-21T10:14:21Z"
  key: "industry"
  item:
  - text: "Standard Industry Codes (SIC) used to classify business establishments and\
    \ other standard units by the type of economic activity in which they are engaged"
    phase: "alpha"
    fields:
    - "industry"
    - "name"
    - "start-date"
    - "end-date"
    register: "industry"
    registry: "office-for-national-statistics"
local-authority:
  index-entry-number: "11"
  entry-number: "11"
  entry-timestamp: "2016-04-21T10:14:21Z"
  key: "local-authority"
  item:
  - text: "Local authorities in England"
    phase: "alpha"
    fields:
    - "local-authority"
    - "name"
    - "website"
    - "email"
    - "address"
    - "start-date"
    - "end-date"
    register: "local-authority"
    registry: "department-for-communities-and-local-government"
public-body:
  index-entry-number: "15"
  entry-number: "15"
  entry-timestamp: "2016-04-21T10:14:21Z"
  key: "public-body"
  item:
  - text: "Ministerial Departments and agencies sponsored by HM Government"
    phase: "alpha"
    fields:
    - "public-body"
    - "name"
    - "website"
    - "public-body-type"
    - "parent-bodies"
    - "text"
    - "crest"
    - "official-colour"
    register: "public-body"
    registry: "cabinet-office"
field:
  index-entry-number: "5"
  entry-number: "5"
  entry-timestamp: "2016-04-21T10:14:21Z"
  key: "field"
  item:
  - text: "Field names which may appear in a register"
    phase: "alpha"
    fields:
    - "field"
    - "datatype"
    - "phase"
    - "register"
    - "cardinality"
    - "text"
    register: "field"
    registry: "cabinet-office"
food-premises-type:
  index-entry-number: "7"
  entry-number: "7"
  entry-timestamp: "2016-04-21T10:14:21Z"
  key: "food-premises-type"
  item:
  - text: "Types of premises which prepare and serve food"
    phase: "alpha"
    fields:
    - "food-premises-type"
    - "name"
    register: "food-premises-type"
    registry: "food-standards-agency"
datatype:
  index-entry-number: "4"
  entry-number: "4"
  entry-timestamp: "2016-04-21T10:14:21Z"
  key: "datatype"
  item:
  - text: "Datatypes constraining values used by register fields and idenitifying ways\
    \ in which it may be encoded a representation"
    phase: "alpha"
    fields:
    - "datatype"
    - "phase"
    - "text"
    register: "datatype"
    registry: "cabinet-office"
school:
  index-entry-number: "18"
  entry-number: "18"
  entry-timestamp: "2016-04-21T10:14:21Z"
  key: "school"
  item:
  - text: "Primary, secondary and special needs schools in England and Wales"
    phase: "alpha"
    fields:
    - "school"
    - "name"
    - "start-date"
    - "end-date"
    - "gender"
    - "religious-character"
    - "minimum-age"
    - "maximum-age"
    - "headteacher"
    - "website"
    - "address"
    register: "school"
    registry: "department-for-education"
premises:
  index-entry-number: "14"
  entry-number: "14"
  entry-timestamp: "2016-04-21T10:14:21Z"
  key: "premises"
  item:
  - text: "Commercial properties eligable for business rates in England and Wales"
    phase: "alpha"
    fields:
    - "premises"
    - "address"
    - "start-date"
    - "end-date"
    register: "premises"
    registry: "valuation-office-agency"
uk:
  index-entry-number: "20"
  entry-number: "20"
  entry-timestamp: "2016-04-21T10:14:21Z"
  key: "uk"
  item:
  - text: "UK and Crown dependencies"
    phase: "alpha"
    fields:
    - "uk"
    - "name"
    - "official-name"
    - "start-date"
    - "end-date"
    - "citizen-names"
    - "text"
    register: "uk"
    registry: "cabinet-office"
company:
  index-entry-number: "2"
  entry-number: "2"
  entry-timestamp: "2016-04-21T10:14:21Z"
  key: "company"
  item:
  - text: "Companies in England and Wales"
    phase: "alpha"
    fields:
    - "company"
    - "name"
    - "company-status"
    - "registered-office"
    - "industry"
    - "start-date"
    - "end-date"
    register: "company"
    registry: "companies-house"
location:
  index-entry-number: "12"
  entry-number: "12"
  entry-timestamp: "2016-04-21T10:14:21Z"
  key: "location"
  item:
  - text: "Geographic locations of places found in government data which may be published\
    \ under an open government licence"
    phase: "alpha"
    fields:
    - "location"
    - "point"
    register: "location"
    registry: "cabinet-office"
government-domain:
  index-entry-number: "9"
  entry-number: "9"
  entry-timestamp: "2016-04-21T10:14:21Z"
  key: "government-domain"
  item:
  - text: "Internet domain names used by HM Government"
    phase: "alpha"
    fields:
    - "government-domain"
    - "owner"
    - "end-date"
    register: "government-domain"
    registry: "government-digital-service"
register:
  index-entry-number: "16"
  entry-number: "16"
  entry-timestamp: "2016-04-21T10:14:21Z"
  key: "register"
  item:
  - text: "Registers maintained by HM Government"
    phase: "alpha"
    fields:
    - "register"
    - "text"
    - "registry"
    - "phase"
    - "copyright"
    - "fields"
    register: "register"
    registry: "cabinet-office"
territory:
  index-entry-number: "19"
  entry-number: "19"
  entry-timestamp: "2016-04-21T10:14:21Z"
  key: "territory"
  item:
  - text: "British English-language names and descriptive terms for territories"
    phase: "alpha"
    fields:
    - "territory"
    - "name"
    - "official-name"
    - "start-date"
    - "end-date"
    - "citizen-names"
    - "text"
    register: "territory"
    registry: "foreign-commonwealth-office"
