---
applications:
- name: beta-multi
  memory: 4GB
  instances: 2
  buildpack: java_buildpack
  health-check-type: http
  health-check-http-endpoint: /healthcheck
  path: ../../openregister-java.jar
  domains:
    - beta.openregister.org
    - register.gov.uk
  hosts:
    - allergen
    - country
    - government-domain
    - government-organisation
    - government-service
    - internal-drainage-board
    - jobcentre
    - jobcentre-district
    - jobcentre-group
    - local-authority-eng
    - local-authority-nir
    - local-authority-sct
    - local-authority-type
    - principal-local-authority
    - prison-estate
    - qualification-assessment-method
    - qualification-level
    - qualification-sector-subject-area
    - qualification-type
    - registration-district
    - statistical-geography
    - statistical-geography-county-eng
    - statistical-geography-london-borough-eng
    - statistical-geography-local-government-district-nir
    - statistical-geography-metropolitan-district-eng
    - statistical-geography-registration-district-eng
    - statistical-geography-registration-district-wls
    - statistical-geography-non-metropolitan-district-eng
    - statistical-geography-unitary-authority-eng
    - statistical-geography-unitary-authority-wls
    - territory
  services:
    - beta-db
    - logit-ssl-drain
  env:
    JBP_CONFIG_JAVA_MAIN: '{ arguments: "server s3://openregister.beta.config/multi/openregister/paas-config.yaml" }'
    AWS_ACCESS_KEY_ID: change-me
    AWS_SECRET_ACCESS_KEY: change-me
    AWS_REGION: eu-west-1
